services:
  web:
    image: cgr.dev/chainguard/nginx:latest
    container_name: nginx
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./code:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/php.conf:/etc/nginx/php.conf
      - ./conf/nginx/site:/etc/nginx/sites-enabled
      - ./log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - code-network
    depends_on:
      - php
  php:
    #image: cgr.dev/chainguard/php:latest-fpm
    build:
      context: ./conf/php
      dockerfile: Dockerfile.chainguard
    container_name: php
    working_dir: /var/www
    restart: always
    volumes:
      - ./code:/var/www
      - ./conf/php/php.ini:/etc/php/php.ini
      - ./conf/php/opcache.ini:/etc/php/conf.d/zz-opcache.ini
      - ./conf/php/php-fpm.conf:/etc/php/php-fpm.d/zzz-php-fpm.conf
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
