version: "3"
services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./code:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/php.conf:/etc/nginx/php.conf
      - ./conf/nginx/site:/etc/nginx/sites-enabled
      - ./log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - code-network
    depends_on:
      - php
  php:
    build:
      context: ./conf/php
      dockerfile: Dockerfile
    restart: always
    container_name: php
    volumes:
      - ./code:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm.conf
    networks:
      - code-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    # following command is required from v8.4.0
    command: --mysql-native-password=ON
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "myrootpassword"
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
