version: "3"
services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./code:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/php.conf:/etc/nginx/php.conf
      - ./conf/nginx/site:/etc/nginx/sites-enabled
      - ./log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
